ExpenseTracker/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace ExpenseTracker.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CategoryController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(this.User);
            var userId = this.GetCurrentUserId();
            var isAdmin = await _userManager.IsInRoleAsync(user, "Admin");
            if (isAdmin)
            {
                return _context.Categories != null ?
                              View(await _context.Categories.Where(c => c.UserId == userId || c.UserId == Guid.Empty).OrderByDescending(c => c.UserId).ToListAsync()) :
                              Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            else
            {
                return _context.Categories != null ?
                              View(await _context.Categories.Where(c => c.UserId == userId).OrderByDescending(c => c.UserId).ToListAsync()) :
                              Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null || _context.Categories == null)
                {
                    return NotFound();
                }

                var category = await _context.Categories
                    .FirstOrDefaultAsync(m => m.CategoryId == id);
                if (category == null)
                {
                    return NotFound();
                }

                return View(category);
            }
            catch (Exception ex)
            {
                return RedirectToRoute("Error");
            }
        }

        // GET: Category/AddOrEdit
        public IActionResult AddOrEdit(int id = 0)
        {
            try
            {
                if (id == 0)
                {
                    return View(new Category());
                }
                else
                {
                    return View(_context.Categories.Find(id));
                }
            }
            catch (Exception ex)
            {
                return RedirectToRoute("Error");
            }
        }

        // POST: Category/AddOrEdit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("CategoryId,UserId,Title,Icon,Type")] Category category)
        {
            try
            {
                var user = await _userManager.GetUserAsync(this.User);
                var userId = this.GetCurrentUserId();
                var isAdmin = await _userManager.IsInRoleAsync(user, "Admin");
                if (ModelState.IsValid)
                {
                    if (category.CategoryId == 0)
                    {
                        //if (isAdmin)
                        //{
                        //    category.UserId = Guid.Empty;
                        //}
                        //else
                        //{
                        category.UserId = userId;
                        //}

                        _context.Add(category);
                    }
                    else
                    {
                        if(category.UserId == userId || isAdmin)
                        {
                            _context.Update(category);
                        }
                    }

                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(category);
            }
            catch (Exception ex)
            {
                return RedirectToRoute("Error");
            }
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null || _context.Categories == null)
                {
                    return NotFound();
                }

                var category = await _context.Categories
                    .FirstOrDefaultAsync(m => m.CategoryId == id);
                if (category == null)
                {
                    return NotFound();
                }

                return View(category);
            }
            catch (Exception ex)
            {
                return RedirectToRoute("Error");
            }
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var user = await _userManager.GetUserAsync(this.User);
                var userId = this.GetCurrentUserId();
                var isAdmin = await _userManager.IsInRoleAsync(user, "Admin");
                if (_context.Categories == null)
                {
                    return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
                }
                var category = await _context.Categories.FindAsync(id);
                if (category != null && (category.UserId == userId || isAdmin))
                {
                    _context.Categories.Remove(category);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return RedirectToRoute("Error");
            }
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }

        private Guid GetCurrentUserId()
        {
            return new Guid(_userManager.GetUserId(this.User));
        }
    }
}

ExpenseTracker/Controllers/DashboardController.cs
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace ExpenseTracker.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DashboardController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                DateTime date = DateTime.Today;

                DateTime StartDate = GetMonthStartDate(date);
                DateTime EndDate = GetMonthEndDate(date);

                ViewData["Date"] = StartDate;

                await PrepareDateForView(StartDate, EndDate);

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToRoute("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(DateTime date)
        {
            try
            {
                DateTime StartDate = GetMonthStartDate(date);
                DateTime EndDate = GetMonthEndDate(date);

                ViewData["Date"] = StartDate;

                await PrepareDateForView(StartDate, EndDate);

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToRoute("Error");
            }
        }

        public async Task PrepareDateForView(DateTime start, DateTime end)
        {
            List<Transaction> SelectedTransactions = await _context.Transactions
                .Include(x => x.Category)
                .Where(y => y.UserId == new Guid(_userManager.GetUserId(this.User)) && y.Date >= start && y.Date <= end)
                .ToListAsync();

            //Total Income
            float TotalIncome = SelectedTransactions
                .Where(i => i.Category.Type == "Income")
                .Sum(j => j.Amount);
            ViewBag.TotalIncome = TotalIncome.ToString("C2");

            //Total Expense
            float TotalExpense = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .Sum(j => j.Amount);
            ViewBag.TotalExpense = TotalExpense.ToString("C2");

            //Balance
            float Balance = TotalIncome - TotalExpense;
            //CultureInfo culture = CultureInfo.CreateSpecificCulture("en-US");
            //culture.NumberFormat.CurrencyNegativePattern = 1;
            //ViewBag.Balance = String.Format(culture, "{0:C2}", Balance);
            ViewBag.Balance = Balance.ToString("C2");

            //Doughnut Chart - Expense By Category
            ViewBag.Expenses = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .GroupBy(j => j.Category.CategoryId)
                .Select(k => new
                {
                    categoryTitleWithIcon = k.First().Category.TitleWithIcon,
                    amount = Math.Round(k.Sum(j => j.Amount),2),
                    formattedAmount = k.Sum(j => j.Amount).ToString("C2")
                })
                .OrderByDescending(l => l.amount)
                .ToList();

            ViewBag.Income = SelectedTransactions
                .Where(i => i.Category.Type == "Income")
                .GroupBy(j => j.Category.CategoryId)
                .Select(k => new
                {
                    categoryTitleWithIcon = k.First().Category.TitleWithIcon,
                    amount = k.Sum(j => j.Amount),
                    formattedAmount = k.Sum(j => j.Amount).ToString("C2"),
                })
                .OrderByDescending(l => l.amount)
                .ToList();
        }

        private DateTime GetMonthStartDate(DateTime date)
        {
            var startDate = new DateTime(date.Year, date.Month, 1);

            return startDate;
        }

        private DateTime GetMonthEndDate(DateTime date)
        {
            var startDate = new DateTime(date.Year, date.Month, 1);
            var endDate = startDate.AddMonths(1).AddDays(-1);

            return endDate;
        }
    }
}

ExpenseTracker/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["ProjectName"] = "Wallet Watch";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["ProjectName"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.syncfusion.com/ej2/20.4.38/bootstrap5-dark.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/ExpenseTracker.styles.css" asp-append-version="true" />*@
    <link href="~/css/layout.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.syncfusion.com/ej2/20.4.38/dist/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["ProjectName"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            @*                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@           
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="">Transactions</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="">Category</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="">Admin</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @ViewData["ProjectName"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</html>